import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar';
import FoldersPage from './components/FoldersPage';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-900 place-content-center">
        <Navbar/>
       
        {children}
        </body>
    </html>
  )
}
